version: '2'
services:
  web:
    build: ./web
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./files:/usr/share/nginx/html/files:ro
    environment:
      - FORCE_SSL='true' #this is read by the haprox loadbalancer, local only
      - API_LINK_ADDR=api
